const fs = require('fs');

fs.readFile('db.json', 'utf8', (err, _data) => {
    if (err) throw new Error(err)
    let data = JSON.parse(_data);
    // first align the new data with the db 
    let nd = newData.map(d => Object.assign({}, {
        id: Number(d.id) + 11,
        name: d.name,
        type: d.type,
        intendedgoal: d.intendedgoal,
        substage: d.substage,
        description: d.description,
        outcome: d.outcome,
        notes: d.notes,
        relatedIntervention: Number(d['Related_Intervention']) + 6,
        relatedStakeholders: d['Related_Stakeholders'].split('\r\n').map(v => Number(v) + 49),
    }));
    data['activities'].push(...nd);
    // console.log(data['activities']);
    // fs.writeFileSync('db.json', JSON.stringify(data));
})

const newData = [
    {
        "id": "1",
        "name": "Network meeting of local service providers",
        "type": "Stakeholder meeting",
        "intendedgoal": "Presenting MobileAge to a network of local service providers and recruit people for our core project group",
        "substage": "Setting up of core-project group",
        "description": "The MobileAge Team in Bremen presented their project to a network of local stakeholders in Bremen Hemelingen, the new field site for the second project phase. The network consists of different local actors and organisation relevant to older adults in the district such as the church in Bremen, social welfare organisations, service centers, city marketing and the police. MobileAge and the idea of a digital district guide – similar to the one developed in Osterholz – was met with a positive response. ",
        "outcome": "First MobileAge project group meeting on 19th April. Further stakeholders will be invited by participants.",
        "notes": "The network meets every six weeks. They are well connected and seem to know each other for a long time. Each of the participants reported from their current activities. Discussions centered around possible synergies between network members. The network also discussed its joint presentation at the district fair in September. \r\n\r\nThis networking event was an ideal opportunity to present MobileAge and engage with active and relevant stakeholders in the district.  ",
        "Related_Intervention": "1",
        "Related_Stakeholders": "1\r\n3\r\n2\r\n4",
        "Related_Apps": "Hemelingen App"
    },
    {
        "id": "2",
        "name": "Cooperation meeting with research project buten aktiv",
        "type": "Cooperation meeting",
        "intendedgoal": "Explore possible synergies with respect to sharing data, field access\r\nExchange experiences",
        "substage": "Exploring and scoping the project",
        "description": "Buten aktiv is a research project run by the public health department of Bremen university. They are conducting their fieldwork in Bremen Hemelingen for 1,5 years now and are well connected in the district. One of the aims of this project is to co-develop with older adults ideas, programmes, information about outdoor activities to improve the relative health in the district. The project will run for another year\r\nWe present our objectives, methodology etc to each other. We then explored possible synergies. Buten aktiv has collected a number of data sets which may be of interested to us:\r\n• Inventory of half of the streets in the district (lightening, security, accessibility)\r\n• A survey with 915 older adults about their neighbourhood and health related topics\r\n• 62 walking interviews (the idea is that we look at these and re-do the most interesting ones) ",
        "outcome": "ButenAktiv will send us their data to assess\r\nAn invitation to older adults about participating in walks will be distributed … Possibility needs to be discussed with FTB concerning feasibility.\r\nWe will have a joint data session and consider possible future collaboration (May, June)",
        "Related_Intervention": "2",
        "Related_Stakeholders": "1\r\n3\r\n2\r\n17\r\n18\r\n19\r\n20",
        "Related_Apps": "Hemelingen App"
    },
    {
        "id": "3",
        "name": "Establishment of core project group",
        "type": "Stakeholder meeting",
        "intendedgoal": "To agree on work plan and time table\r\nTo consider further recruiting  ",
        "substage": "Setting up of core-project group",
        "description": "We presented the project to Ms Bonjer which we hadn’t met before and then started planning our collaboration.\r\nAs the district consists of five distinct neighbourhoods we discussed how these may be represented. We also discussed how Turkish older adults (biggest minority) may be reached and Ms. Schüdde will be in contact with a Turkish social club.",
        "outcome": "We will conduct 5-6 focus groups with older persons to present the results from our work in Osterholz and discuss what older residents in Hemeling like and dislike. They are schedule between 22nd to 24th May. In a subsequent meeting these focus groups will consider what objects/information may be relevant to their district. Participants will be provided with cultural probes (still to be developed by us).\r\nThe next meeting will be on 10th May, after a networking meeting. The participants will recruit further members for our core group and invite them.",
        "notes": "The approach to work with a core group of local stakeholders seems to work well. Ms. Akkermann confirmed that involving certain groups of older people (e.g. with mental health problems) only for 1 or 2 events better suits their needs. This maybe a key to ensuring represenativeness and inclusiveness for more vulnerable groups of older adults.",
        "Related_Intervention": "3",
        "Related_Stakeholders": "1\r\n3\r\n7\r\n8\r\n9",
        "Related_Apps": "Hemelingen App"
    },
    {
        "id": "4",
        "name": "Press meeting & kick-off",
        "type": "Dissemination event",
        "intendedgoal": "To officially launch the project kick-off with core project group \r\nTo gain support from local administration due to positive press coverage and local stakeholder buy in",
        "substage": "Setting up of core-project group",
        "description": "1. We informed about the current activities in Bremen Hemelingen and stated that we were looking for more collaborators in the core group. The next meeting is scheduled on 10th May.  \r\n2. We promoted a survey conducted by the city marketing in collaboration with MobileAge in which residents are asked about restaurants, lunch deals etc. This information is to be included in our app.\r\n3. We presented the results from our activities in Bremen Osterholz on a multi-touch table. The table will now circulate in various locations in Osterholz. ",
        "outcome": "The attendants were very interested in the possibilites a multi-touch table offers. We discussed whether a table or a board are better suited (question of space in meeting places vs wheel chair accessibility). Overall, such interactive display seem to be an engaging way to ensure ensure the inclusiveness and accessibility of the table. \r\nThere was also a brief discussion on making the app available in different languages (e.g. Turkish). Frau Schüdde will follow-up with the Turkish cultural association.",
        "notes": "We need to further discuss different aspects for acquiring tables (e.g. where are they placed best, who benefits from those).\r\n\r\nSuch meetings are important to the local stakeholders that become involved. Many of the welfare organisations and service providers are under financial pressure. Opportunities to promote their work for the district are vital and a great way to value their engagement.   ",
        "Related_Intervention": "4",
        "Related_Stakeholders": "1\r\n3\r\n6\r\n10\r\n8\r\n7\r\n11\r\n12",
        "Related_Apps": "Hemelingen App"
    },
    {
        "id": "5",
        "name": "District fair",
        "type": "Dissemination event",
        "intendedgoal": "Dissemination of results\r\nRecruitment for 2nd phase\r\nCommitment from actors in Hemeling",
        "substage": "Transfer and dissimination",
        "description": "Present our application on a multi-touch table during a district fair. ",
        "outcome": "Very few people stopped.",
        "notes": "Such fairs do not seem to be the appropriate place for disseminating project outcomes. The table will now go on a tour through different lunch clubs / cafés. We expect the results to be better. ",
        "Related_Intervention": "5",
        "Related_Stakeholders": "3\r\n6\r\n21\r\n22",
        "Related_Apps": "Hemelingen App"
    },
    {
        "id": "6",
        "name": "2nd core project group meeting",
        "type": "Stakeholder meeting",
        "intendedgoal": "To plan and organise the first focus groups with respect to content and concept\r\nTo consider further recruiting  ",
        "substage": "Continuous recruitment",
        "description": "We presented the project to Ms Schilling which we hadn’t met before \r\nWe discussed how older adults from the different neighbourhoods with different abilities and interests can be recruited for the focus groups.",
        "outcome": "A first group, organised by Karin Schüdde, will take place on the 22nd. For further groups Ms Schilling will address further stakeholders in the different neighbourhoods.\r\nWe learned that the limitation of the mobility patterns and interests of the majority of (older) people in the district is also a social issue: Socially disadvantaged people are more likely to have a narrower radius. Therefore it is important to provide information on the district as a whole and not separated into neighbourhoods. This might arouse interest in other neighbourhoods among the citizens and widen their spatial and social radius. This needs to be taken into account when organising focus groups and designing probes.  \r\nThe next meeting will be on 9th June OR 13th June, after a networking meeting. The participants will recruit further members for our core group and invite them.",
        "notes": "The participants of the core group are very excited about the project and motivated to contribute to its success. Despite some time delays because of absence of important local stakeholders the participants were optimistic to be able to recruit older adults for the co-creation process. The recruitment of minority groups like people with migration background is seen as challenge: The representatives of these groups are very reserved towards these kind of “inclusion”.  ",
        "Related_Intervention": "6",
        "Related_Stakeholders": "1\r\n3\r\n2\r\n7\r\n13\r\n23",
        "Related_Apps": "Hemelingen App"
    },
    {
        "id": "7",
        "name": "Network meeting of local service providers",
        "type": "Stakeholder meeting",
        "intendedgoal": "Further recruitment of local service providers for our core project group.",
        "substage": "Continuous recruitment",
        "description": "Karin Schüdde from the church in Hemelingen and coordinator introduced MobileAge to those, who did not know the project before. The members of the network then proposed us to contact people they knew and that might be interested in the project.   ",
        "outcome": "List of names of potentially interested stakeholders in the district. ",
        "notes": "In contrast to the first time we went to this network meeting, this time was not very successful. The network members were not very motivated to help themselves in the recruitment but rather named other persons",
        "Related_Intervention": "7",
        "Related_Stakeholders": "2\r\n4",
        "Related_Apps": "Hemelingen App"
    },
    {
        "id": "8",
        "name": "1st focus group with older adults (Hemelingen)",
        "type": "Focus group\r\n",
        "intendedgoal": "To engage older adults in the project.\r\nTo get feedback on the relevance of the content of the technical result from Osterholz.",
        "substage": "Idea forming",
        "description": "We presented the project and filled out the consent forms. \r\nWe talked about the question were participants get information about the district. \r\nWe showed the digital district guide from Osterholz and discussed it\r\nWe worked with printed screenshots of the district guide in order to alienate people that may feel intimidated by using a tablet. The focus was on the content, and we worked on the following tasks\r\n- Are the categories on the front page the important topics? What is missing?\r\n- Is the content under each topic what you expected it to be? What is missing?\r\n- Are the attributes appropriate to describe the places in the respective category?\r\n- Are the information relevant at all? Can you find them somewhere else? \r\nWe discussed relevant topics in the district for older adults.\r\nWe determined the date for the next focus group\r\nWe handed out cultural probes",
        "outcome": "Recruitment and engagement of 2 participants for the neighbourhood Hemelingen\r\nOverview of important information sources available in the district.  \r\nInformation on toilets and benches as very important\r\nThe category `sport’ should be renamed to a broader term like “exercise” or “movement/motion”\r\nHealth might be a topic to implement, but this needs further discussion (e.g. does everyone know, where the next pharmacy, doctor, etc. is, or are such information relevant on a district level? Are there other information that might be relevant in this category?)\r\nWe agreed on the 13th June 2017 as date for the next focus group. We also agreed to contact the two newspapers that have previously covered our activities, in order to publicly announce the next focus group.",
        "notes": "The social activities manager of the local protestant church and project team member had advertised the project and organized the focus group. She had put out a flyer and addressed people personally. Two older adults from the neighbourhood attended the meeting. One of them, Mr. Meyer, had already participated in phase one in Osterholz. He is part of the project team and very valuable for us as an expert in different areas: He knows the project and the outcome from the first phase, he knows Hemelingen very well, he engages active in Openstreetmap and will provide us with geo data on places and he is very skilled with ICT’s. He supports us with the organization and implementation particularly of the data collection. Furthermore, he is attending all the focus groups. The other participant was a woman aged 75 who had just moved to the neighbourhood some month ago. Before, she had lived in another neighbourhood in Hemelingen. Besides the social activity manager from the church, two ifib researchers participated. The focus group took place in the community building of the protestant church of the district, hostet by the project group member who had organized the meeting. \r\nWe started by telling something about the project. The female participant was quite interested in the question of demographic change, how it affects society and if it is a problem in other countries as well. She seemed very interested and she filled out and signed the consent form. She started to talk about the district and things she dislikes about it. She, for example, engages in cleaning the neighbourhood by picking up waste and she complained about dog dirt that dog owners would leave in the street. She also complained about the closing of retail stores and said that instead more and more hairdressers would open up. This was commented by the social activity member, who said that the reason might be all the men who would care about shaving a lot (which somehow seemed to be a reference to men with migration background). Furthermore, the female participant does volunteer work looking after people with mental health problems, which was her profession before she retired. She presented herself as not interested in the use of digital technologies: “I don’t need this anymore”. However, it turned out that her daughter tries to convince her to use a smartphone and that she has tried several times. When we encountered some problems with the tablets, she was relieved: “Oh I thought this would only happen to me. I am happy to see, that also other people face these problems”.\r\nWe started to talk about the information sources available and used in the district. Since she does not use the internet, for the female participant different kind of print media are her primary information source. She also said that she gets her information by getting around in the district (“first hand”) and by talking to people. For the other participant besides print media, Google is an important information source also regarding events in the district.\r\nThe female participant is very knowledgeable about the district. She knows lots of places and people. No matter what topic we addressed, she knew something to tell about it from the district perspective. Obviously, she preferred talking about places and people than about categories and attributes as we had planned to do. Therefore we had a lively discussion, which was difficult to steer in the direction we had planned.  \r\nThe social activities manager raised the question, if a category like “health”, where for example pharmacies would be shown, would not be important to include in the district guide. However, we finally agreed, that most people would know the pharmacies and doctors close to them. The same applies to for example shops.\r\nWhen we talked about the category “sport” the participant said, that in her opinion a broader term like ‘exercise’ would be better, because “sport” makes her think of football and other more “fun” oriented or institutionalized forms of exercise, whereas for older adults health related kinds of exercise are much more important.  \r\nThe relevance of the category “nice places” was confirmed. The participants furthermore stressed the importance of (information on) benches and toilets for this category. Interestingly she told that even if the need for toilets is a problem for almost all older people this is mostly addressed by men. \r\nThe female participants rides a bike, which is “not a normal but a special kind of bike”. She also uses public transportation. \r\n\r\nThe recruitment of an “open” focus group (in addition to the recruitment of existing groups) did not work well. Only one participant had come. We will announce the next focus group in the newspaper to reach more people. \r\nIt was difficult to steer the discussion. Maybe the small size of the group was one aspect of this. \r\nThe female participant is particularly competent and knowledgeable regarding the district and hence very well suited for the data-creation phase. ",
        "Related_Intervention": "8",
        "Related_Stakeholders": "1\r\n2\r\n24\r\n23\r\n7",
        "Related_Apps": "Hemelingen App"
    },
    {
        "id": "9",
        "name": "1st focus group with older adults (Sebaldsbrück)",
        "type": "Focus group\r\n",
        "intendedgoal": "To engage older adults in the project.\r\nTo get feedback on the relevance of the content of the technical result from Osterholz.",
        "substage": "Idea forming",
        "description": "We presented the project and filled out the consent forms. \r\nWe talked about the question were participants get information about the district. \r\nWe showed the digital district guide from Osterholz and discussed it\r\nWe worked with printed screenshots of the district guide in order to alienate people that may feel intimidated by using a tablet. The focus was on the content, and we worked on the following tasks\r\n- Are the categories on the front page the important topics? What is missing?\r\n- Is the content under each topic what you expected it to be? What is missing?\r\n- Are the attributes appropriate to describe the places in the respective category?\r\n- Are the information relevant at all? Can you find them somewhere else? \r\nWe discussed relevant topics in the district for older adults.\r\nWe determined the date for the next focus group\r\nWe handed out cultural probes",
        "outcome": "Recruitment and engagement of 2 participants for the neighbourhood Hemelingen\r\nOverview of important information sources available in the district.  \r\nInformation on toilets and benches as very important\r\nThe category `sport’ should be renamed to a broader term like “exercise” or “movement/motion”\r\nHealth might be a topic to implement, but this needs further discussion (e.g. does everyone know, where the next pharmacy, doctor, etc. is, or are such information relevant on a district level? Are there other information that might be relevant in this category?)\r\nWe agreed on the 13th June 2017 as date for the next focus group. We also agreed to contact the two newspapers that have previously covered our activities, in order to publicly announce the next focus group.",
        "notes": "Monia Akkermann had promoted the project among a group of 35 people with mental health problems. 5 interested people had shown up for the focus group: One woman and 4 men, one of them fits the image of a “senior citizen” the other 4 people seemed relatively young (maybe 40-50 years old). The focus group was held in a nice and bright room in the day care center of ASB, where people from all over the district can come during the day to meet others, We started by telling something about the project. \r\n- One male (ca. 50 years old) who is working fulltime in sheltered workshops, does not use internet or any digital devices and seems quite worried about many things. He could express himself very well, but often brought-up different very personal topics. \r\n- One male (ca 50) who was very reluctant and quiet and does not use internet or any digital devices. He left before we finished but took a probes bag and promised to come to the next meeting\r\n- One male (ca. 50) who almost did not say anything. He has written in the “e-mail address” column on the participants list “am interested, but FAIL in the USAGE”\r\n- One male (ca 70) who uses the internet and works as volunteer\r\n- One female (ca 45) who is experienced with digital media and calls herself a “profi when it comes to the internet”. She was very open minded and told us that she has already “made a website herself”. She is passionate hobby photographer and has problems with social contacts. She was very determined that she did not want to be photographed. \r\nBefore starting the audio record, we handed out the consent forms. The participants seemed a bit overburdened with it and we decided to let them take it home and fill it out there. They all gave us verbal consent for the audio record. \r\nDuring the whole session a lot of questions popped up, like \r\n- what the connection to English cities are\r\n- why we need something digital when there are lots of printed information\r\n- why in the guide for Osterholz there are lot of things not only interesting for older but also younger people\r\nThe cultural probes seemed to surprise the participants and rise interest for the project.\r\nThe consent form is barely reasonable and too difficult to understand. It made people feel like participating would mean to consent to a lot of dangerous things with consequences they cannot really estimate.\r\nDue to very different attention spans and difficulties to focus on one topic “classical” workshops tools like printed handouts or pin board did not work. An open discussion seemed most appropriate. However, some participants would only say something if addressed directly. \r\nTalking about concrete places that people know was much more interesting for the participants then talking about abstract “topics” or “attributes”. Hence, the group seems very fit for data collection. ",
        "Related_Intervention": "9",
        "Related_Stakeholders": "2\r\n3\r\n9\r\n23\r\n25\r\n26\r\n27\r\n28\r\n29",
        "Related_Apps": "Hemelingen App"
    },
    {
        "id": "10",
        "name": "1st focus group with older adults (Arbergen)",
        "type": "Focus group\r\n",
        "intendedgoal": "To engage older adults in the project.\r\nTo get feedback on the relevance of the content of the technical result from Osterholz.",
        "substage": "Idea forming",
        "description": "We presented the project and filled out the consent forms. \r\nWe talked about the question were participants get information about the district. \r\nWe showed the digital district guide from Osterholz and discussed it\r\nWe worked with printed screenshots of the district guide in order to alienate people that may feel intimidated by using a tablet. The focus was on the content, and we worked on the following tasks\r\n- Are the categories on the front page the important topics? What is missing?\r\n- Is the content under each topic what you expected it to be? What is missing?\r\n- Are the attributes appropriate to describe the places in the respective category?\r\n- Are the information relevant at all? Can you find them somewhere else? \r\nWe discussed relevant topics in the district for older adults.\r\nWe determined the date for the next focus group\r\nWe handed out cultural probes",
        "outcome": "Arouse interest among 6 participants from Arbergen\r\nThe main problem/topic for these people is mobility and physical accessibility. Many of them have reduced mobility (cannot walk long distances, have problems with stairs, etc.) and they lack possibilities to go somewhere. An idea for the service is to extend the district guide on places and institutions with more detailed information on access and mobility (e.g. information/communication on support services and benefits, on connecting routes from and to stations, car and taxi sharing) for the respective places.\r\nThe category “sport” should be renamed\r\nWe agreed on the 6th June 2017 as date for the next focus group.",
        "notes": "The focus group took place in the meeting room of the residence. 6 residents had come, most of them are in the tablet group of the residence and hence know how to use internet and tablet. The director of the home and member of the project team introduced the ifib team and then left. \r\nWe introduced the project and ourselves. Then the participants introduced themselves and where asked to tell why they were interested in the project. The participants were 1 married couple that lives in the residence for two years, all the other female participants were single (mostly widowed), they moved to the residence between 10 to 2 years ago. All participants lived in Bremen for a long time, though most of them had lived in different districts before moving to the residence home. Overall the residence is home to 11 married couples and 16 single women (out of which 13 are over 80 years). One of our participants established a monthly “talking café” for these single women, where they meet and talk. All agreed that these social contacts were of great importance. Someone said that these conversations “make you mobile”/”move you” and that too little was done for the “soul”. All the others agreed. They also repeatedly stated that there was only very little to do in the close proximity of the care home (e.g. no cafés, no shops) as opposed to what some of the participants were used to when they still lived in the city centre. \r\nThe participants also told us that they plan for a few joint excursions per year. Asked how they obtain information about their destination, they replied that they usually only ever go to places they know and that they would like to visit again. \r\nAs for technology, most of them were interested in technology and affirmed that they use their tablets regularly. One participant did not use a tablet at all but stated her interest when asked. One female participant mentioned that she started working with a computer in 1992. Overall, the participants seemed well educated and well-off. Several participants mentioned that they had sold their houses in order to move to the residence. Repeatedly, participants made reference to their work life.\r\nWe skipped the handout of consent forms, since it would have interrupted the flow of discussion. It seemed that they had read the information brochure carefully and had thought about the project.Many of them were quite critical about the project, because as they said “not the information about places and institutions is the problem, but that you won’t get there”. Some of the participants cannot walk long distances and use a rollator. For them the biggest problem is getting to the bus/tram station and from the station to their destination. Most of them use Taxi when they really need to go somewhere (e.g. to the doctor), but can’t afford to use it often (e.g. for leisure activities). Other participants are very mobile and some of them have a car. Between the participants there seemed a good atmosphere: It seemed they all liked, respected and helped each other. However, the idea of sharing a car or taxi  triggered some reservation as they were not convinced that it would work, because as they said most other residents in the home wouldn’t be able to plan and coordinate such things. It seems that these people are very active, interested and solidary group as distinguished from the rest of the residents. It turned out that some of them didn’t know about certain support services that they are eligible for (e.g. rollator courses from the public transport operators, new regulations state support benefits). \r\nWith the handout of the screenshots as well as tablets the participants looked at the digital district guide for Osterholz. Overall, it seemed to make a very good impression and consolidated the people’s interest in our project. Like in the first focus group the participants didn’t like the term “sport” for the category for physical activities. One woman argued: “sport sounds too much like performance and exhausting”. For them especially health-oriented activities like kneipp cure or activities like pottery are interesting.\r\nFinally, we handed out consent form to be filled out until the next meeting and cultural probes. It was a little difficult to determine a date for our next meeting. As some of the participants are very busy. Almost all of them had to consult their diaries.\r\n\r\nThe participants were critical about our idea to develop and provide technology that should solve their problems. They experience their needs more as a lack of infrastructure than a lack of information.\r\nThe participants were very open minded, active and engaged. They themselves reminded us that they are not representative for all residence and that most people in the residence are much more passive, disinterested and immobile. ",
        "Related_Intervention": "10",
        "Related_Stakeholders": "1\r\n2\r\n3\r\n36\r\n8\r\n23\r\n30\r\n31\r\n32\r\n33\r\n34\r\n35",
        "Related_Apps": "Hemelingen App"
    },
    {
        "id": "11",
        "name": "2nd focus group with older adults (Arbergen)",
        "type": "Focus group",
        "intendedgoal": "We wanted to present some results from a small research on mobility support in Bremen in order to give the participants confidence that we take their problems seriously, even if we cannot solve them\r\nWe wanted to look at the printed district guide and ask the participants to complement it with places that it does not contain yet",
        "substage": "Idea forning\r\n* Collect, validate and quality check data",
        "description": "We discussed \r\n• the relevance of a district guide for the participants\r\n• participants local knowledge \r\n• the cultural probes\r\nWe collected the cultural probes",
        "outcome": "Lesson learned about the specificity of older adults living in residences.\r\nWithdrawing the collaboration by mutual consent ",
        "notes": "The focus group again took place in the meeting room of the residence. The same 6 residents had come (one arrived a little late) and Mr. Meyer was there.\r\nWhile we waited for the last participants to come, a discussion unfold about children playing on the area of the residence. The participants complained about the noisy and naughty children. \r\nWhen everyone had arrived one female participant started saying, that they all wanted to say something regarding the cultural probes and the whole project. She particularly complained about the cultural probes, that she called the “the shock bag”. The main critique points that everyone agreed on were the size of the map (nobody could read it), which they experienced as an unreasonable demand because they simply could not recognize anything and furthermore as an impertinence because it seemed to them we did not have thought about it and willingly had brought them in an unpleasant situation. The postcard where the participants were asked to draw an emblem for the district also arouse anger. It seemed that at least one of the participants viewed this as a ridiculous task. The main point of all of them was, that the extent of the probes (time to invest, things we wanted to know, etc.) was so huge that it scared them and pressurized them, what made them upset.\r\nWe had brought a tablet to borrow it to one of the participants who did not use the internet or any digital devices yet and we had understood that she was interested in doing so. She refused to take it and when asked, said that she had been joking about wanting one. She said that she was too old to start using it and absolutely did not want to. Later she said about the project that she feels as if our goal is to persuade them to use online media, and she stated “And this I don’t want!”\r\nOverall the whole group does not feel like participating in the project would be beneficial for whether them nor for us. The only male participant emphasized, that they lack knowledge about the district, because all of them have not been there for a long time and therefor would not be able to support us.\r\nIn the end, we collected the probes and said goodbye by mutual consent that a collaboration is not beneficial for either of us.\r\nSince we did not get any consent by them, we did not audio record the session.\r\n\r\nWe have to think about the great differences between a group of relatively young, independent living, mobile and active older people and people living in residences. With higher age and physical decline people seem to have completely different needs and attitudes. To start working solely with a group of active older adults restricts the outcome to a very certain user group and excludes others. Hence, we need to address questions of (scarce) resources. \r\nFurther reflection of the cultural probes and the contexts in which to use them is needed. ",
        "Related_Intervention": "11",
        "Related_Stakeholders": "3\r\n2\r\n8\r\n23\r\n30\r\n31\r\n32\r\n33\r\n34\r\n35",
        "Related_Apps": "Hemelingen App"
    },
    {
        "id": "12",
        "name": "3rd core project group meeting",
        "type": "Stakeholder meeting",
        "intendedgoal": "To reflect on the completed activities, to plan and organize further focus groups \r\nTo consider further recruiting  ",
        "substage": "Continuous recruitment",
        "description": "We talked about the experiences in the different focus groups and the cultural probes\r\nWe discussed how we can understand a diverse district like Hemelingen and how we can organize a project across the different neighbourhoods",
        "outcome": "We learned about the motives and attitudes of the participants from the group in Arbergen to reject the project and the cultural probes (e.g. the probes made them aware of their deficits)\r\nWe learned about the district, the reasons for its divides and how to take this into account in the materials (e.g. divide the probes map into neighbourhoods)\r\nWe were invited to present the project to the Ortsbeirat\r\nKarin Schüdde is organizing walking tours (on the 30th of June, 15th and 30th of August)\r\nGaby Dönselmann is organizing a focus group with volunteers working with people with dementia",
        "notes": "The project meeting has shown, that a more intense exploration of the socio-spatial conditions of a field site is necessary:\r\n1. We need to understand the district, it’s spatial and social divisions, the reasons and effects of this divides\r\n2. We need to know the people better before designing probes for them\r\nThe cultural probes do not work the same way for different older adults. For some people they might be too personal (consider revising the name and age) and people have privacy concerns. We have to make sure before handing them out, that every task is doable (in terms of font size, complexity, extent and willingness). Therefor it might be important to know the participants better when designing the probes and to look at them jointly and explain them before handing them out. \r\nFurthermore local specifics need to be considered (e.g. in Hemelingen it does not make sense to have one map of the whole district but better one map for each neighbourhood). The division between the neighbourhoods are stronger than we had expected. 20 years ago people from Hemelingen and Arbergen wouldn’t even talk to each other (e.g. children were sitting in separate parts of a classroom), today this is getting better but the distance remains (socio-demographic differences). The local service providers encourage us to develop something for the whole district in order to support and facilitate their efforts to unite the district.\r\nFurthermore we were advised not to talk too much about what we did in Osterholz, since there is some kind of comparison and competition between the two districts",
        "Related_Stakeholders": "1\r\n2\r\n7\r\n13\r\n23\r\n14\r\n8",
        "Related_Apps": "Hemelingen App"
    },
    {
        "id": "13",
        "name": "2nd focus group with older adults (Hemelingen)",
        "type": "Focus group",
        "intendedgoal": "To complement the data from the printed district guide",
        "substage": "Collect, validate and quality check data",
        "description": "To look at the printed district guide and ask the participants to complement it with places that it does not contain yet",
        "outcome": "Information on nice places and walks in Hemelingen\r\nIdea and agreement for next intervention to be a walk in the neighbourhood",
        "notes": "One new participant had come to the meeting. She is a very well looking woman that makes the impression of an intelligent, competent and autonomous woman that is actively engaged in different activities (e.g. sport and related tours to Berlin, volunteer work). She lives in Hemelingen for 50 years and is in her own perspective one of the few people that cross the borders in the district. Hence, she is very knowledgeable about all neighbourhoods and very interested in the district’s development and image. When talking about information sources, she makes clear that she knows where to get information (“I just go there and ask”), but she is aware that other older adults “are fearful” and “don’t dare to go somewhere” because they feel unsecure. Hence, her motivation to participate is that she wants to help people to reduce uncertainties through the provision of information and thereby support their mobility and social life/strengthens their confidence. We talked about the cultural probes first and handed out a bag to the new participant. Later the participants from the first meeting arrives. We talked about places in the district by looking and the map together and later planned the routes for the walks. The participants advised us not to plan the walk for more than two kilometres. Then we decided to include a joint lunch and/or coffee and cake in the walking tours. The idea is that, when we walk together along nice places the people will talk about the places and thereby deliver data for the description. One big topic were people with migrant background, especially girls wearing scarf what is seen as a symbol of oppression.\r\n\r\nThe two participants in this group are knowledgeable residents of Hemelingen that identify with the district, care about its image and are interested in uniting the different neighbourhoods. In this respect, they differ very much from the group in Arbergen and are perfectly qualified for the data collection. Interestingly none of them complained about the cultural probes. ",
        "Related_Intervention": "13",
        "Related_Stakeholders": "1\r\n3\r\n24\r\n37\r\n7\r\n23",
        "Related_Apps": "Hemelingen App"
    },
    {
        "id": "14",
        "name": "2nd focus group with older adults (Sebaldsbrück)",
        "type": "Focus group",
        "intendedgoal": "To complement the data from the printed district guide",
        "substage": "Collect, validate and quality check data",
        "description": "Presentation and discussion of the project\r\nTo look at the printed district guide and ask the participants to complement it with places that it does not contain yet\r\nTo collect the cultural probes",
        "outcome": "Information on interesting places in Hastedt",
        "notes": "Observation notes\r\nOnly one participants (m) from the last meeting of this group had come. He was the only one of the group that I would have identified as “older adults”. He lives in Hasted and had brought a befriended couple that also lives in Hastedt. One of the other participants (m) from the last meeting called me later to apologize for not beeing there. He wanted to come, but couldn’t do it. He told me on the phone that he had filled out the probes and offered to send it via post. \r\nWe started by talking about the project since the new participants didn’t know about it. The other participant had shown the cultural probes and the brochure to them and they were interested. No one of them had filled out the probes. And the participant from the last meeting also didn’t want to fill out the consent form even if he is very interested and engaged.\r\nThe conversation returned to the segregation of the district of Hemelingen. All three participants live in Hasted which is very close to the inner part of the city. They emphasized that Hasted is very different to the other neighbourhoods in Hemelingen and that it is much more urban than the rest. They feel much closer to the district that borders Hastedt in the west, which one of the most popular districts of Bremen. It seemed that the rest of Hemelingen to them is either rural and boring or socially problematic. These people, especially the couple, seem to be well educated, open minded, healthy and active (e.g. sport clubs). The woman told that she had used a computer for work but since twenty years does not use it, because she doesn’t like to. It seems that for her life should more take place in “reality” than via media. However, she and her husband were interested in the project and wanted to take a look at the district guide for Osterholz.\r\nTogether we looked at the Hastedt part of the printed district guide, discussed the relevance of the places and added further missing places. Most of the nice and interesting places for them however do not belong to Hemelingen, but to the inner parts of the city which in their case is their direct neighbourhood. \r\nIn the end the participants who had already been in the first meeting brought up the topic of lacking skills regarding digital media and the internet amongst older people. He asked if this shouldn’t be the first step before doing a project like ours. He reported of problems he had had himself (e..g. with sending emails from his smartphone) and how he had tried to get help from his son/son-in-law on the phone. He complained that “young people” do not understand the problems older people have and that his younger relatives are too impatient to help him. I recommended him to go to a computer club for older adults if he would need help and could convince him of the relevance of our project anyway. \r\n\r\nThe three participants are very active and knowledgeable people. However, their knowledge about the district is limited since they are more oriented to the city center. But they seemed to be at least interested in getting to know other party of Hemelingen.",
        "Related_Intervention": "14",
        "Related_Stakeholders": "2\r\n29\r\n37\r\n38\r\n23\r\n9",
        "Related_Apps": "Hemelingen App"
    },
    {
        "id": "15",
        "name": "1st district walk with older adults (Tamra)",
        "type": "Walking Workshop",
        "intendedgoal": "To identify relevant attributes for walking routes (what information older adults need on walking routes)\r\nTo raise trust and interest on the project",
        "substage": "Developing a rough service concept",
        "description": "Walking together along a route in the district\r\nTo fill out a questionnaire on relevant attributes\r\nJoint lunch",
        "outcome": "List of relevant attributes and learning about other interesting topics\r\nAccess to older adults in the district\r\nDate for a subsequent workshop to evaluate the walk and define the attributes",
        "notes": "We met at the protestant church in the morning. Despite constantly rain xx older adults from the district had shown up to join the walk. We had chosen a route from the printed district guide and promoted the walk in the newspapers, via the intermediaries and in an online event calendar. We had chosen to promote the walk as a joint walk through the district in the first place, in order to keep the barriers for participation low. \r\nWe started with a short introduction of the project. Then we started walking along the route. On our way we came across a senior resident home and picked up two more participants. One of them has a mobility device. This woman showed us a hidden garden we didn’t had planned to visit. We further came along the “Bürgerhaus” which is an important place in the district (events, coffee, meeting people), walked through a park which is quite disputed (some people like it and other totally dislike it) and other places. One participant is quite new in the district. She moved there from another German city, because her children live there and they wanted to be able to take care of her. She told us that she misses her old city and her social contacts there, but is very eager to get to know people in her new environment (e.g. bridge group). All the others have lived in the district for a long time and are very knowledgeable about it. They had a lot to tell about the historical developments in the district, which turned out to be a main point of interest, when walking. \r\nOn the half way we made a coffee break in the “Bürgerhaus”, where the particioants were asked to fill out the questionnaire on attributes. Many of them said, that they were not very interested in attributes for accessibility but much more in the history of places.\r\nWe continued the walk through another park and came across a “Geschirrmanufaktur”, whose former owner is a very known person in the district. Then we had lunch at a restaurant/café called “Eisen werner” which had been an iron shop and a very institution in the district before. After closing the iron shop a second hand shop had reopened combindes with a restaurant and café where they serve lunch for low prices.\r\nWhile eating lunch again people talked a lot about the history of the district and their personal stories. When we wanted to show the Osterholz district guide on the tablet in the end, the participants were reluctant but then showed some interest and positive reactions. \r\nWe had planned to hand out the amended cultural probes, but together with the intermediary we decided not to give them out at this point, since we were afraid it would be to much. We gave out the information brochures and then discussed a date for our next meeting. Again the patricipants were reluctant to commit themselves to come, but most said they wanted to try.\r\n\r\nAfter our experiences with the last focus groups we decided to be more slowly with giving information on the project and asking people to commit themselves to certain task and the project. It seems that it is very important first to get to know the people and the district, to raise trust and interest, before asking people for their engagement. \r\nTo walk together, talk about the district and its history and to show interest in the people and what they want to talk about seems to be very important in order to raise trust. We almost didn’t talk about technology. ",
        "Related_Intervention": "15",
        "Related_Stakeholders": "1\r\n2\r\n3\r\n40\r\n41\r\n42\r\n23\r\n43\r\n44\r\n45\r\n37\r\n24\r\n46\r\n7",
        "Related_Apps": "Hemelingen App"
    },
    {
        "id": "16",
        "name": "4th core project group meeting",
        "type": "Stakeholder meeting",
        "intendedgoal": "To establish a data structure \r\nTo identify and define data sources and arrange related tasks",
        "substage": "Developing a rough service concept",
        "description": "Considering datasources, define data structure and arrange tasks for data collection\r\nDiscussing potential intermediaries to organize another walk\r\nNext steps\r\nNext meeting",
        "outcome": "We agreed on Mrs. Hillmann as primary data source for POIs \r\nWe agreed on the categories “walks”, “nice places”, “meeting places”, “culture/education”, “exercise”, “counselling” + additional categories to be considered: “neighbourhood”, “bike tours” and “gastronomy”\r\nThe members of the project group are not willing to take the responsibility for the validation and supplement of the Hillmann data. Beke Herbst will try to recruit a older adults group. Heike Schilling will do the task for her neighbourhood. Institutions will be asked to amend their data themselves.\r\nIdea and potential intermediaries for another walk (Hastedt)\r\nStrategy for promoting the next walk\r\nAgreement on a joint appearance on the district fair in September",
        "notes": "The project meeting has shown, that it is difficult to hand over responsibility to the intermediaries.",
        "Related_Intervention": "16",
        "Related_Stakeholders": "1\r\n3\r\n7\r\n23\r\n36\r\n13\r\n8\r\n10\r\n15",
        "Related_Apps": "Hemelingen App"
    },
    {
        "id": "17",
        "name": "Debriefing session on 1st district walk (Tamra)",
        "type": "Focus group",
        "intendedgoal": "To debrief the results (Attributes and data) from the 1st walking workshop (ID\r\nTo discuss examples on displaying routes and related information\r\nTo plan the next walking route\r\nTo develop another walking route",
        "substage": "Developing a rough service concept",
        "description": "Presentation and discussion of the results of the questionnaire from the walk\r\nDiscussion and collection of a) interesting places and b) accessibility issues on the route of the last walk \r\nPresentation on the “accessible city guide” on the official city portal as example for displaying walking routes\r\nParticipants discuss and agree on another walking route (in Seebaldsbrück)\r\nParticipants define the route for the next walk (Arbergen)",
        "outcome": "Another walking route in another neighbourhood (Seebaldsbrück)\r\nData collection of POIs and accessibility issues on the route of the first walk",
        "notes": "We met at the protestant church in the afternoon. Besides Günther Meyer 3 participants from the Hemelingen walk had come. We started to present the results from the walk. The participants did not seem to remember or be interested in them. Also the presentation of the example of digital walking routes did not seem to elicit great interest. The participants listened and looked at it, but did not have any opinion on whether they liked it or not. By contrast – when talking about the last walk and the POI’s on the way they were eager in talking about them and sharing their knowledge. In particular one of the participants was very active. Sometimes it was even difficult to make her stop talking. This participants also came up with the idea for another walk in Seebaldsbrück. When defining the route for the next step the participants jointly worked on the route together with Karin Schüdde and without any intervention of the researchers.\r\n\r\nThe small number of participants and the limited interest of those who were there shows that recruitment was not successful. It seems that some of the participants are solely interested in the walking and not at all in the development of an application. However, once again the focus shifts to the co-creation of data.",
        "Related_Intervention": "17",
        "Related_Stakeholders": "1\r\n2\r\n36\r\n23\r\n46\r\n45\r\n24\r\n7",
        "Related_Apps": "Hemelingen App"
    },
    {
        "id": "18",
        "name": "Meeting with P+T bureau for urban planning",
        "type": "Collaboration meeting",
        "intendedgoal": "The project “accessible city guide Bremen” creates accessible routes through Bremen through the detailed measure of routes and possible barriers and their description. MobileAge would like to collaborate with them on the Co-creation of age-friendly walks in Hemelingen.",
        "substage": "Create and integrate (open) data",
        "description": "To present MobileAge and our concern to the project members.\r\nTo discuss possible collaboration.\r\n",
        "outcome": "The project team is interested in our project. They will calculate the efforts, costs and financing for conducting a survey for one or more walks in Hemelingen in the frame of the project “accessible city guide Bremen”.",
        "Related_Intervention": "18",
        "Related_Stakeholders": "1\r\n3\r\n2\r\n16\r\n47",
        "Related_Apps": "Hemelingen App"
    },
    {
        "id": "19",
        "name": "2nd district walk with older adults (Hasenpromenade)",
        "type": "Walking Workshop",
        "intendedgoal": "To collect data on interesting places and issues along the route",
        "substage": "Create and integrate (open) data",
        "description": "Walking together along a route in the district\r\nTo audio record the statements of participants along the route\r\nTo map the interesting places\r\nCoffee and cake\r\n",
        "outcome": "Audio records of information on interesting places and areas on the route\r\nCollection of interesting spots along the route\r\nFurther recruitment\r\nConcept for a cultural-historical walk in Arbergen\r\n",
        "notes": "Seven participants had shown up at the meeting point. Three new participants had come, one of them (m) is about to set up a group for historical research on the district. This participant had a lot of personal as well as historical stories and anecdotes to tell about the different areas we passed on the way. He is a valuable source of information on Arbergen. However, it seemed that some of the participants that had already been involved in the first walk felt disregarded, because he put himself in the foreground. Since we were audio recording the talking on the walk, the microphone even seemed to intensify the resentment in the group: The dominant participant closely stayed with the microphone all the time, while the group split into two or more small groups. After a while the intermediary asked the participant to withhold a bit and the confidence improved and there was a nice atmosphere while walking, watching and talking. \r\nWhile finally drinking coffee together it was again difficult to stop the participants from giving a talk. However, he agreed with us to organize another walk in Arbergen that he will lead anf that will focus on the historical development of the neighbourhood.\r\nIn the end we wanted to hand out consent forms but most participants didn’t want to even take a look at it.\r\n\r\nIn order to fully capture the statements of the participants at least one more microphone is necessary. This might also prevent the resentment in the group. \r\nAgain it shows that a loose group with new participants joining from time to time is not the ideal approach. \r\n\r\n",
        "Related_Intervention": "19",
        "Related_Stakeholders": "1\r\n3\r\n40\r\n7\r\n10\r\n48\r\n49\r\n45\r\n46\r\n24\r\n29\r\n50",
        "Related_Apps": "Hemelingen App"
    },
    {
        "id": "20",
        "name": "Data capture on 1st district walk (Tamra)",
        "type": "Data collection",
        "intendedgoal": "To collect data material (audio, video, photography’s, text) on the route and the interesting places along the route",
        "substage": "Create and integrate (open) data",
        "description": "Walking together along the route of the first walk\r\nTo audio and video record the statements of participants along the route\r\nTo write down information on interesting places\r\nTo take pictures of the route and the places along\r\n",
        "outcome": "Audio and video records of information on interesting places and areas on the route.\r\nPictures of the route\r\n",
        "notes": "Three participants had come. They were asked by the BO-team for consent to be filmed. Two of the participants agreed, one of them didn’t want to be filmed and photographed. Mrs. Schüdde agreed to be filmed. On the different places along the route we stopped and Mrs. Schüdde and the participants were asked to tell something. Mrs. Schüdde mostly told about the history of places and what is interesting about them at present (e.g. what programmes there are). The participants also told a lot about history and present of the destinations but further added some personal biographical anecdotes that they connect with the respective place. \r\nThe participants did not seem to be disturbed by the cameras or microphones. They seemed to enjoy being heard and even recorded. \r\nIn the end we had coffee in one of the destinations along the route – a former specialist retailer on iron that now is a second hand shop and café. This place everyone in the district seems to know and while having coffee all of the participants shared their quite nostalgic memories on that shop.    \r\n\r\nThe recording worked better than we had expected. None of the participants felt intimidated by the recording equipment. ",
        "Related_Intervention": "20",
        "Related_Stakeholders": "1\r\n2\r\n52\r\n53\r\n54\r\n7\r\n42\r\n23\r\n51\r\n24",
        "Related_Apps": "Hemelingen App"
    },
    {
        "id": "21",
        "name": "Co-creating a district walk (ID 25)",
        "type": "Focus group",
        "intendedgoal": "To plan and organize another district walk with knowledgeable older adults from the district",
        "substage": "Create and integrate (open) data",
        "description": "Discussing possible routes and interesting places\r\nMap the route and find a date for the walk",
        "outcome": "Concept for a historical walk in the neighburhood Hastedt",
        "notes": "We had invited 3 older men from the district. Two of them has been recommended to us from the \"Alte Vielfalt\", one had participated in the project before. It turned out that one of them was a historian, who was able to give very structured and detailled information. The other two told us very personal stories, but were not able to participate in a structured planning. It would have been better to meet seperately with the 3 people since they have very different areas of knowledge and abilities.",
        "Related_Intervention": "21",
        "Related_Stakeholders": "1\r\n2\r\n55\r\n56\r\n29",
        "Related_Apps": "Hemelingen App"
    },
    {
        "id": "22",
        "name": "3rd district walk with older adults (Schlengpark)",
        "type": "Walking Workshop",
        "intendedgoal": "To collect data on interesting places and issues along the route",
        "substage": "Create and integrate (open) data",
        "description": "To audio record the statements of participants along the route\r\nTo map the interesting places\r\nCoffee and cake",
        "outcome": "Audio records of information on interesting places and areas on the route\r\nCollection of interesting spots along the route\r\nThe idea to organize tablet groups (including tablet introduction) for the design stage",
        "notes": "The walk was not very productive wrt. Data creation. The park seems not to be very popular amongst older adults and the areas around it are quite normal residential areas. ",
        "Related_Intervention": "22",
        "Related_Stakeholders": "1\r\n2\r\n5\r\n7\r\n57\r\n46\r\n42\r\n23\r\n51\r\n24\r\n58\r\n36",
        "Related_Apps": "Hemelingen App"
    },
    {
        "id": "23",
        "name": "5th core projectgroup meeting",
        "type": "Stakeholder meeting",
        "intendedgoal": "To update the core project group on the progress conducted walks, meetings etc.) and to plan the next steps (tablet groups, data co-creation)",
        "substage": "Continuous recruiting of additional co-creators\r\nDetailing service concept\r\nIdentifying existing data\r\nCollecting, validating & quality checking data",
        "description": "The project group was updated with the progress of the project in Hemelingen and the further procedure was planned.\r\n1. Update project progress \r\na. Previous walks\r\nb. Planned walks\r\nNo walk in Mahndorf planned so far due to lack of Mahndorf participation. Karin Schüdde is trying to make contact.\r\nc. Blog\r\nd. Other Activities\r\ne. Data\r\nf. Videos\r\n2. further planning\r\na. Implementation of the district guide / tablet groups\r\n",
        "outcome": "Agreement on procedure and dates for tablet groups: \r\nRegularly weekly meetings meetings for learning, content management and design\r\nAgreement on responsibilities: \r\nThe Ifib team manage the groups and are responsible for the content\r\nFTB is responsible for design issues\r\nKarin Schüdde is responsible for dissemination, recruitment and facilities",
        "Related_Intervention": "23",
        "Related_Stakeholders": "1\r\n2\r\n7\r\n8\r\n9\r\n36\r\n14\r\n23",
        "Related_Apps": "Hemelingen App"
    },
    {
        "id": "24",
        "name": "4th district walk with older adults (Schlosspark)",
        "type": "Walking Workshop",
        "intendedgoal": "To collect data on interesting places and issues along the route",
        "substage": "Create and integrate (open) data",
        "description": "To audio record the statements of participants along the route\r\nTo map the interesting places\r\nCoffee and cake",
        "outcome": "Audio records of information on interesting places and areas on the route\r\nCollection of interesting spots along the route",
        "notes": "5 older adults had come to walk with us. One of them, Grete Bald, said, that she wasn't very knowledgeable herself about the area, which was one of the reasons for her to participate. Ralf Rot took pictures of the walk. Recurring themes were the history of the parc and the outdoor pool, the old trees, other plants along the way. In the end we talked abouot the tablet groups and new media in general. Rudolf Hansen, who had come for the first time said he was very interested in the tablet groups, but does not have enough time at the moment. He seemed quite skilled in ICT.",
        "Related_Intervention": "24",
        "Related_Stakeholders": "1\r\n2\r\n36\r\n7\r\n23\r\n24\r\n59\r\n60\r\n61",
        "Related_Apps": "Hemelingen App"
    },
    {
        "id": "25",
        "name": "5th district walk with older adults (Arbergen)",
        "type": "Walking Workshop",
        "intendedgoal": "To collect data on interesting places and issues along the route\r\nTo recruit participants for tabletgroups",
        "substage": "Continious recruitment of additional co-creators\r\n* Create and integrate (open) data",
        "description": "To audio record the statements of participants along the route\r\nTo map the interesting places\r\nTo recruit co-creators for tablet groups\r\nLunch",
        "outcome": "12 potential participants for tablet groups\r\n",
        "notes": "Horst Weise who had participated in the 2nd district walk had offered to prepare and to lead a cultural-historic walk through the neighbourhood Arbergen. He is very much interested in the development of the former farming village into the neighbourhood it is today. When we arrived around 30 people had come to listen to Horst Weise. He had announced the walk on his own, without mentioning the project. Most participants therefor were not primarily interested in our project. Also most of the time Horst Weise was the only speaker. Hence, the audio records are not very useful to us. \r\nHowever, for lunch there were only around 20 people left. Before lunch we introduced the project and announced the tablet groups. 12 new and 4 already active paricipants added their names on the list for beeing interested in the tablet group.\r\n\r\nThe experience again shows, that it is important not to start the recruitment with introducing the project and technology, but to start from an existing practice, then to get in touch with people and afterwards to connect this practice to the project and possible technological solutions. ",
        "Related_Intervention": "25",
        "Related_Stakeholders": "1\r\n2\r\n7\r\n23\r\n58\r\n62\r\n63\r\n64\r\n65\r\n66\r\n67\r\n42\r\n50\r\n68\r\n24\r\n69\r\n70\r\n71\r\n72",
        "Related_Apps": "Hemelingen App"
    },
    {
        "id": "26",
        "name": "1st tablet workshop with older adults",
        "type": "Tablet workshop",
        "intendedgoal": "To introduce participants in the use of tablets and apps",
        "substage": "Creating & integrating data",
        "description": "To introduce participants to tablet computers and the use of apps\r\nTo give out tablets to participants and encourage them to use them on their own",
        "outcome": "Encouraged \"non-users\" to explore the use of tablet computers and developed basic skills",
        "notes": "Unfortunately only three out of six registered participants came to the workshop. We started by handing out the consent forms and broschures and to talk about the project. The participants filled out the forms. Then we started talking about their previous experiences with digital devices and/or the internet. One of them, Eva Warnke, has never used any digital device before. Ulrich Bäcker uses an ipad, a smartphone and computer and Rita Rübe has few experiences with smartphohe and computer. Mrs. Warnke told us, that her daughter had given her a smartphone some time ago, but that she had given it back, because she did not know how to use it and felt let alone with it. She was involved in the project from the beginning on. When we had talked about tablets, internet and so on in the beginning she had been very rejecting and had told us that she did not want to have anything to do with this. During the walks we had got to know each other and she had become much more talkative and open minded. In the workshop she constantly repeated that she would probably be too stupid and too slow to understand it and that she would just try it out but did not want to promise that she would continue with using the tablet. She obviously had the impression that she would be dismissed from the participation, when she would fail in handling the tablet. We assured her that it was not our concern to test her, but that it would be our own failure if we wouldn't succeed in teaching her the use. We also assured that she commited herself to nothing and that she could stop at any time. \r\nWe had prepared an instruction for the basic functionalities of the tablet. Along this we jointly turned on the device, entered the pin codes and started to look at the start page. While one of the researchers showed and explained the steps another one was sitting besides Mrs. Warnke and helped her follow. Then we asked the participants which of the installed apps (Mobileage prototype, Youtube, GoogleMaps, Chrome, camera, galery, public transport) they were most interested in. Rita Rübe wanted to explore Youtube.  The handling of the Youtube app turned out to be callenging: Finding the search box was difficult, since you only see the symbol and first when touching it, it opens up. When playing a video it was hard for them to know how to stop it since the play button disappears after a while and only appears again when touching the screen. And the function that - while searching for another video - the video continues in a small screen in the lower corner of the display confused them. Eva Warnke expressed her fear that she would never be able to get along with the tablet on her own. On the question if there was no tablet or coputer group for older adults in the distrcit she answeared that there was one but it was booked out already. \r\nThese kind of in-between-talks always led to discussion among the participants about the district, where something is, who comes from what neighbourhood and so on. Interestingly one of the, Eva Warnke, comes from the neighbourhhod Hemelingen, the other two from Arbergen. It was very interesting to see how they freely talked about their mutual prejudices and started to make fun of it together and theryby to overcome them. However, we as facilitators did not want to interrupt these kind of talks but on the other hand wanted to continue with our agenda. We succeeded in doing so when taking the topic of their discussion as starting point and relate it to the technology. For instance when talking about were the computer classes for older adults take place, we showed them GoogleMaps and so they could directly show the other one on the map where something is located. When we explored GoogleMaps it turned out that even Mr. Bäcker who had used the app some times, did not know that it is possible to navigate with it. We then tried out the app of the public transportation, which worked quite well.  \r\nAfter an hour of working with the tablets we asked if they still wanted to try some more or if it was enough. Mrs. Rübe wanted to try out the camera app, but Mrs. Warnke said that \"her head was buzzing\" and that she was not able to take in more information.\r\nFinally we gave out some broschures for senior citizens starting to use tablets and the charging cable for the tablet. Mrs. Warnke had a lot of questions, like what happend when the tablet got stolen and the like. She seemed really nervous and excited at the same time. She also asked what all of this would cost her, and was positive surprised, that the EU covers all the cost. We also told them to call us if they had any problems they needed help with. For instance in case of a system update or any other sudden message that appears it seemed to us that they needed a contact person.\r\n\r\nThe group size was not too big at all, more people would have made it much harder especially for those who don't have any experiences. In order to reduce the feeling of uncertainty or even fear a one-to-one support seems necessary. Different levels of competencies make it much more difficult. We have to think about, how to continue and how to deal with these disparities without leaving someone behind.",
        "Related_Intervention": "26",
        "Related_Stakeholders": "2\r\n73\r\n42\r\n64\r\n66",
        "Related_Apps": "Hemelingen App"
    },
    {
        "id": "27",
        "name": "6th  district walk with older adults (Hastedt)",
        "type": "Walking Workshop",
        "intendedgoal": "To explore a historical walk through the district and collect data on historically intersting places.\r\nTo recruit further participants",
        "substage": "Create and integrate (open) data",
        "description": "To audio and video record the historical information on the neighbourhood provided by Joachim Dietrich",
        "outcome": "Audio- and video material on the history of the neighbourhood",
        "notes": "Joachim Dietrich, graduate historian and expert on the history of Bremen and espeecially the neighbourhood Hastedt guided the group along historical interesting places. The bremen Online team audio and video recorded the walk and will provide videos for the different places along the route.",
        "Related_Intervention": "27",
        "Related_Stakeholders": "1\r\n2\r\n52\r\n53\r\n7\r\n55\r\n50\r\n51\r\n56\r\n29\r\n23\r\n24\r\n70\r\n42\r\n66",
        "Related_Apps": "Hemelingen App"
    },
    {
        "id": "28",
        "name": "2nd Tablet workshop with older adults",
        "type": "Tablet workshop",
        "intendedgoal": "To bring all participants on the same level, building a group and prepare them for the upcoming design phase\r\nTo agree on content and functionalities",
        "substage": "Identifying independent areas of desired functionality\r\nAgreeing on functionality to be implemented",
        "description": "To present maps and pictures from the walks and thereby recap the conducted activities\r\nTo present the draft plan for the upcoming co-design phase and discuss design ideas for the display of walks",
        "outcome": "Commitment to the project among participants\r\nA shared vision of the result (app)\r\nIdentified desire for filter (nature/nice walks and historical walks) and for implementing \"virtual walks\" (video that captures the walk i.e. with Mapillary)\r\n",
        "notes": "We started with a welcome and introduction round were we again presented the project and participants introduced themselves. We had prepared a presentation on the walks we have conducted so far. Since few participants had participated in all the walks, we wanted to recap the conducted activities and give a first impression of the material collected. At the same time mapping the walks and adding pictures gave them an impression of the app we want to develop. The participants enjoyed to see an interim outcome of the activities and seemed to get an impression of the goal of the field work. We then looked at different examples for mapping and editing digital walks/places. we also showed the Osterholz App which the participants really liked. Afterwards we had a discussion were some participants came up with first design ideas (filter for nature/nice walks and historical walks and for implementing \"virtual walks\" (video that captures the walk i.e. with Mapillary)). Finally we presented the draft agenda for the design phase and agreed on the dates. In the end we handed out tablets to those participants who do not have their own and who had not been in the first tablet group. Eva Warnke who had had her first intercation with a dgital device in the first tablet group had used the tablet several times at home but found it too frustrating and gave the tablet back. However she still wants to participate.",
        "Related_Intervention": "28",
        "Related_Stakeholders": "1\r\n2\r\n23\r\n42\r\n24\r\n72\r\n71\r\n70\r\n67",
        "Related_Apps": "Hemelingen App"
    },
    {
        "id": "29",
        "name": "Survey of accessability aspects for 1st district walk (ID 15)",
        "type": "Data collection",
        "intendedgoal": "To survey barriers on the route/create data on the accessability of the walk",
        "substage": "Create and integrate (open) data",
        "description": "Measure longitudinal and transverse inclinations as well as edges and capture the surface and map the data. ",
        "outcome": "Data on accessibility of the route. ",
        "notes": "It was interesting to learn, how the experts measure the environment and asses the data as problematic/not problematic. We learned a lot about accessibility and it's description. ",
        "Related_Intervention": "29",
        "Related_Stakeholders": "2\r\n3\r\n16\r\n74",
        "Related_Apps": "Hemelingen App"
    },
    {
        "id": "30",
        "name": "3rd Tablet workshop with older adults",
        "type": "Tablet workshop",
        "intendedgoal": "To develop first drafts on display/interfaces for visualising the walks",
        "substage": "Prototyping & implementation",
        "description": "Short presentation on the areas/aspects to be desgines\r\nPaper prototyping with Mock-ups",
        "outcome": "Paper Mock-ups for screens on 1. an overview over all walks in the map, 2. a detailed map on a single walk, 3. deatailed information on a single walk",
        "notes": "Six participants had come to the workshop. FR had prepared a short presentation where he showed, what we wanted to work on (drafts for the different views/screens of the walks). He had also prepared blank templates on tablet screens as well as buttons, map backgrounds, texts, symbols and so forth to glue them on the screens. We had brought scissors, pencils, paper. After the presentation the idea was that the participants form groups and together with the researchers worked on the screens. They seemed quite reluctant in the first place. We then asked, if they felt like doing the paper work themselves or if they would prefer to discuss in the whole group and let us do the paper work, what trhey preferred. So we gathered around some flipcharts and started discussing the first screen (an overview over all walks in the map). It turend out that there was a productive mix of different competecncies amongst the participants: The men were very much interested in the technical output and showed to have experience in navigating sites and reflecting on their own experiences. In addition the woman contributed a social dimension to the discussion. Ursula Greve who is member of the local advisory council, said that it would be very important to have a overview over the whole district with all it's different neighbourhoods on the first screen, in order to counteract the segregation of the district and foster a district wide sense of community. \r\nDoing the paper-prototyping the participants engaged actively in the discussions around the disposition of the different elements. And again it became clear that ICT-skilled participants are much more well suited for design questions, whereas participants with no or low ICT-experience tend to discuss more content related aspects. ",
        "Related_Intervention": "30",
        "Related_Stakeholders": "1\r\n2\r\n36\r\n70\r\n72\r\n42\r\n71\r\n23\r\n24",
        "Related_Apps": "Hemelingen App"
    }
]